### PR TITLE
implement deploy task and add option for dev build

### PR DESCRIPTION
**Pull request by KP2048**

### CODE REVIEW

**Comment by KP2048** [comment]
for the dev builds, the rollup config for each plugin should be updated to this
```js
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import typescript from '@rollup/plugin-typescript';
import { defineConfig } from 'rollup';
import importAssets from 'rollup-plugin-import-assets';

import { name } from "./plugin.json";
import {createPathTransform} from "rollup-sourcemap-path-transform";
const production = process.env["RELEASE_TYPE"] !== 'development'

export default defineConfig({
  input: './src/index.tsx',
  plugins: [
    commonjs(),
    nodeResolve(),
    typescript(),
    json(),
    replace({
      preventAssignment: false,
      'process.env.NODE_ENV': JSON.stringify('production'),
    }),
    importAssets({
      publicPath: `http://127.0.0.1:1337/plugins/${name}/`
    })
  ],
  context: 'window',
  external: ['react', 'react-dom'],
  output: {
    file: 'dist/index.js',
      sourcemap: !production ? 'inline' : false,
      sourcemapPathTransform: !production ? createPathTransform({
          prefixes: {
              "../src/": `/plugins/${name}/src/`,
              "../node_modules/.pnpm/": `/plugins/${name}/node_modules/`
          },
          requirePrefix: true
      }) : undefined,
      footer: () => !production ? `\n//# sourceURL=http://localhost:1337/plugins/${name}/frontend_bundle` : "",
    globals: {
      react: 'SP_REACT',
      'react-dom': 'SP_REACTDOM',
    },
    format: 'iife',
    exports: 'default',
  },
});
```

**Comment by KP2048** [comment]
if the plugin devs don't update their rollup config, things will still work, it won't break the ci, they just won't be able to make dev builds

**Comment by Witherking25** [comment]
if the plugin devs don't update their rollup config, things will still work, it won't break the ci, they just won't be able to make dev builds

**Comment by SkyLeite** [comment]
Looks good. I have a few nitpicks but they’re not related to functionality so I can loop around to them myself later. Thanks for the contribution :)

**Pull request merged**
